// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyFinder.Persistence.Entities;

#nullable disable

namespace PartyFinder.Persistence.Entities.Migrations
{
    [DbContext(typeof(PartyFinderDBContext))]
    [Migration("20260104163314_prelobbystatestring")]
    partial class prelobbystatestring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityServerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LobbyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreLobbyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QueuePartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("PreLobbyId");

                    b.HasIndex("QueuePartyId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("PartyFinder.Persistence.Entities.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Boss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("PartyFinder.Persistence.Entities.PreLobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Boss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InviteToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxSize")
                        .HasColumnType("int");

                    b.Property<string>("PreLobbyState")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TargetSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PreLobbies");
                });

            modelBuilder.Entity("QueueParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Boss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<int>("TargetSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QueueParties");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.HasOne("PartyFinder.Persistence.Entities.Lobby", "Lobby")
                        .WithMany("Members")
                        .HasForeignKey("LobbyId");

                    b.HasOne("PartyFinder.Persistence.Entities.PreLobby", "PreLobby")
                        .WithMany("Members")
                        .HasForeignKey("PreLobbyId");

                    b.HasOne("QueueParty", "QueueParty")
                        .WithMany("Members")
                        .HasForeignKey("QueuePartyId");

                    b.Navigation("Lobby");

                    b.Navigation("PreLobby");

                    b.Navigation("QueueParty");
                });

            modelBuilder.Entity("PartyFinder.Persistence.Entities.Lobby", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PartyFinder.Persistence.Entities.PreLobby", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("QueueParty", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
