<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PartyFinder.Persistence.Entities\PartyFinder.Persistence.Entities.csproj" />
    <ProjectReference Include="..\PartyFinder.Persistence\PartyFinder.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Hubs\" />
    <Folder Include="Mapping\" />
  </ItemGroup>

</Project>
