using System.Globalization;

namespace BudgetApp.App.Localization;

/// <summary>UI language is independent of the device's date and number culture.</summary>
public static class L
{
    private static readonly IReadOnlyDictionary<string, string> Keys = new Dictionary<string, string>
    {
        ["Valuta"] = "CurrencyLabel",
        ["Transactie toevoegen"] = "Text001",
        ["Boek een inkomst of uitgave op je rekening."] = "Text002",
        ["Rekening"] = "Text003",
        ["Omschrijving"] = "Text004",
        ["Bedrag (€)"] = "Text005",
        ["Type"] = "Text006",
        ["Categorie"] = "Text007",
        ["Datum"] = "Text008",
        ["Opslaan"] = "Text009",
        ["Vernieuwen"] = "Text010",
        ["Je budgetten"] = "Text011",
        ["Stel per maand en categorie een limiet in. Opnieuw opslaan werkt die limiet bij."] = "Text012",
        ["Maand"] = "Text013",
        ["Limiet (€)"] = "Text014",
        ["Budget opslaan"] = "Text015",
        ["Nog geen gegevens."] = "Text016",
        ["Geselecteerd budget verwijderen"] = "Text017",
        ["Maand {0}"] = "Text018",
        ["Rekening aanmaken"] = "Text019",
        ["Je eerste rekening"] = "Text020",
        ["Voeg een rekening toe om je inkomsten en uitgaven bij te houden."] = "Text021",
        ["Rekeningnaam"] = "Text022",
        ["Bijvoorbeeld: Zichtrekening"] = "Text023",
        ["Rekeningtype"] = "Text024",
        ["Beginsaldo"] = "Text025",
        ["Vul het huidige saldo van deze rekening in."] = "Text026",
        ["Dashboard"] = "Text027",
        ["Je overzicht"] = "Text028",
        ["Je inkomsten en uitgaven, helder op een rij."] = "Text029",
        ["Opnieuw proberen"] = "Text030",
        ["Netto deze maand"] = "Text031",
        ["Je ingestelde inkomen plus extra inkomenstransacties, min de uitgaven van deze maand. Dit is niet je rekeningsaldo."] = "Text032",
        ["Waar gaat je inkomen naartoe?"] = "Text033",
        ["Cirkeldiagram: oranje is uitgegeven, paars is over. De bedragen staan hieronder."] = "Text034",
        ["Oranje: uitgegeven · Paars: over"] = "Text035",
        ["Bij een tekort is de cirkel volledig oranje. Het negatieve nettobedrag staat hierboven."] = "Text036",
        ["Inkomsten"] = "Text037",
        ["Uitgaven"] = "Text038",
        ["Nog geen inkomen of uitgaven. Leg je inkomen vast of voeg een transactie toe."] = "Text039",
        ["+  Transactie toevoegen"] = "Text040",
        ["Instellingen"] = "Text041",
        ["Over / tekort: € {0:N2}"] = "Text042",
        ["Je historiek"] = "Text043",
        ["Bekijk de maanden waarin je gegevens hebt vastgelegd."] = "Text044",
        ["Maand bekijken"] = "Text045",
        ["Inkomen"] = "Text046",
        ["Je inkomen"] = "Text047",
        ["Leg je inkomen vast en kies vanaf wanneer het geldt."] = "Text048",
        ["Geldig vandaag"] = "Text049",
        ["Inkomen vastleggen"] = "Text050",
        ["Geldig vanaf"] = "Text051",
        ["Dit inkomen telt vanaf de ingangsdatum mee op je dashboard. Voer hetzelfde bedrag niet ook als inkomenstransactie in; die tellen als extra inkomsten."] = "Text052",
        ["Inkomen opslaan"] = "Text053",
        ["Je inkomenshistoriek"] = "Text054",
        ["Nog geen inkomen vastgelegd."] = "Text055",
        ["Vanaf {0:dd/MM/yyyy}"] = "Text056",
        ["Maanddetails"] = "Text057",
        ["Ingesteld inkomen en extra inkomsten, min de uitgaven van de maand."] = "Text058",
        ["Inkomsten: € {0:N2}"] = "Text059",
        ["Uitgaven: € {0:N2}"] = "Text060",
        ["Netto: € {0:N2}"] = "Text061",
        ["Je spaardoelen"] = "Text062",
        ["Volg je voortgang. Een bijdrage hier verplaatst geen geld tussen rekeningen."] = "Text063",
        ["Naam"] = "Text064",
        ["Doelbedrag (€)"] = "Text065",
        ["Al gespaard (€)"] = "Text066",
        ["Doeldatum"] = "Text067",
        ["Nieuw doel / bewerken annuleren"] = "Text068",
        ["Geselecteerd doel bewerken"] = "Text069",
        ["Bijdrage voor geselecteerd doel (€)"] = "Text070",
        ["Voortgang bijwerken"] = "Text071",
        ["Geselecteerd doel verwijderen"] = "Text072",
        ["Gespaard: € {0:N2}"] = "Text073",
        ["Doel: € {0:N2}"] = "Text074",
        ["Behaald: {0}"] = "Text075",
        ["Behaald"] = "Text076",
        ["Nog bezig"] = "Text077",
        ["Je spaargeld"] = "Text078",
        ["De saldi van je spaarrekeningen, overzichtelijk bij elkaar."] = "Text079",
        ["Spaardoelen bekijken"] = "Text080",
        ["Je transacties"] = "Text081",
        ["Selecteer een transactie om ze te verwijderen."] = "Text082",
        ["Geselecteerde transactie bewerken"] = "Text083",
        ["Geselecteerde transactie verwijderen"] = "Text084",
        ["Transactie niet gevonden."] = "Text085",
        ["Transactie bewerken. De oorspronkelijke rekening blijft behouden."] = "Text086",
        ["Maak eerst een rekening aan."] = "Text087",
        ["Kies een rekening en datum en vul een omschrijving in."] = "Text088",
        ["Transactie opgeslagen."] = "Text089",
        ["Nog geen budgetten ingesteld."] = "Text090",
        ["Kies een maand."] = "Text091",
        ["Budget opgeslagen."] = "Text092",
        ["Selecteer eerst een budget."] = "Text093",
        ["Budget verwijderen"] = "Text094",
        ["Dit budget verwijderen?"] = "Text095",
        ["Verwijderen"] = "Text096",
        ["Annuleren"] = "Text097",
        ["Vul een rekeningnaam in."] = "Text098",
        ["Vul een geldig beginsaldo in volgens je toestelinstellingen."] = "Text099",
        ["Kies een rekeningtype."] = "Text100",
        ["De rekening kon niet worden opgeslagen. Probeer opnieuw."] = "Text101",
        ["Je overzicht kon niet worden geladen. Probeer opnieuw."] = "Text102",
        ["Selecteer een maand."] = "Text103",
        ["Nog niet geladen"] = "Text104",
        ["Nog geen geldig inkomen"] = "Text105",
        ["Het inkomen kon niet worden geladen. Probeer opnieuw."] = "Text106",
        ["Vul een bedrag groter dan nul in met maximaal twee decimalen."] = "Text107",
        ["Kies een ingangsdatum."] = "Text108",
        ["Er bestaat al een inkomen met deze ingangsdatum. Kies een andere datum."] = "Text109",
        ["Opslaan is mislukt. Probeer opnieuw."] = "Text110",
        ["Je inkomen is opgeslagen."] = "Text111",
        ["Opgeslagen, maar het overzicht kon niet worden vernieuwd. Klik op Vernieuwen."] = "Text112",
        ["Maandoverzicht"] = "Text113",
        ["Geen transacties in deze maand."] = "Text114",
        ["Spaardoel aanmaken"] = "Text115",
        ["Selecteer eerst een spaardoel."] = "Text116",
        ["Wijzigingen opslaan"] = "Text117",
        ["Maak je eerste spaardoel aan."] = "Text118",
        ["Vul een naam en doeldatum in."] = "Text119",
        ["Gebruik maximaal 100 tekens voor de naam."] = "Text120",
        ["Spaardoel opgeslagen."] = "Text121",
        ["Voortgang bijgewerkt."] = "Text122",
        ["Spaardoel verwijderen"] = "Text123",
        ["Dit spaardoel verwijderen?"] = "Text124",
        ["Spaardoel verwijderd."] = "Text125",
        ["Nog geen spaarrekening. Maak er een aan om hier je saldo te zien."] = "Text126",
        ["De actie is mislukt. Probeer opnieuw."] = "Text127",
        ["Vul een geldig bedrag in met maximaal twee decimalen."] = "Text128",
        ["Jouw voorkeuren"] = "Text129",
        ["Maak de app prettig voor jou. Je keuze wordt automatisch bewaard."] = "Text130",
        ["Weergave"] = "Text131",
        ["Thema"] = "Text132",
        ["Taal"] = "Text133",
        ["Licht"] = "Text134",
        ["Donker"] = "Text135",
        ["Nog geen transacties. Voeg je eerste transactie toe."] = "Text136",
        ["Selecteer eerst een transactie."] = "Text137",
        ["Transactie verwijderen"] = "Text138",
        ["Deze transactie verwijderen en het saldo-effect terugdraaien?"] = "Text139",
        ["BudgetApp"] = "Text140",
        ["Transacties"] = "Text141",
        ["Budget"] = "Text142",
        ["Sparen"] = "Text143",
        ["Meer"] = "Text144",
        ["Historiek"] = "Text145",
        ["Spaardoelen"] = "Text146",
        ["Rekeningen laden..."] = "Text147",
        ["Laden mislukt"] = "Text148",
        ["De rekeningen konden niet worden geladen. Herstart de app om opnieuw te proberen."] = "Text149",
        ["OK"] = "Text150",
        ["Je bewerkt: {0}"] = "Text151",
        ["{0} actieve doelen · {1} behaald"] = "Text152",
        ["Bijvoorbeeld: {0:N2}"] = "Text153",
        ["Naam is verplicht."] = "Text154",
        ["Naam is verplicht. (Parameter 'value')"] = "Text155",
        ["Bedrag mag maximaal twee decimalen bevatten."] = "Text156",
        ["Inkomen moet groter zijn dan 0."] = "Text157",
        ["Doelbedrag moet groter zijn dan 0."] = "Text158",
        ["Huidig bedrag mag niet negatief zijn."] = "Text159",
        ["Budgetbedrag moet groter zijn dan 0."] = "Text160",
        ["Bedrag moet groter zijn dan 0."] = "Text161",
        ["Datums en getallen volgen je toestelinstellingen."] = "Text162",
    };

    public static string Get(string key) => TextResources.Get(key, AppLanguage.IsEnglish);

    public static string T(string text) => Keys.TryGetValue(text, out var key) ? Get(key) : text;

    public static string Format(string text, params object[] values)
    {
        var format = T(text);
        if (format.Contains('€'))
            format = format.Replace("€", AppCurrency.Symbol, StringComparison.Ordinal);
        return SystemValueFormatter.Format(format, values);
    }

    public static string ValidationMessage(ArgumentException exception)
    {
        var message = exception.Message;
        var parameterSuffix = message.IndexOf(" (Parameter", StringComparison.Ordinal);
        if (parameterSuffix >= 0) message = message[..parameterSuffix];
        if (Keys.ContainsKey(message)) return T(message);
        // Validation raised by a ViewModel has already been translated.
        if (!AppLanguage.IsEnglish || Keys.Values.Any(key => Get(key) == message)) return message;
        return T("De actie is mislukt. Probeer opnieuw.");
    }
}
