<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
    <PackageReference Include="Duende.IdentityModel.OidcClient" Version="7.0.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.11.10" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Stripe.net" Version="50.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PartyFinder.Api.Contracts\PartyFinder.Api.Contracts.csproj" />
    <ProjectReference Include="..\PartyFinder.Domain.Services\PartyFinder.Domain.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\" />
  </ItemGroup>
</Project>
